# Generated by Django 4.0.4 on 2022-07-08 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images/cat/')),
            ],
        ),
        migrations.CreateModel(
            name='Pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('decription', models.CharField(blank=True, max_length=80)),
                ('img', models.ImageField(blank=True, upload_to='images/pics/')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallary.cat')),
            ],
        ),
    ]
