# Generated by Django 4.0.4 on 2022-07-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='p_height',
            field=models.PositiveIntegerField(blank=True, default=360),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pics',
            name='p_height',
            field=models.PositiveIntegerField(blank=True, default=360),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cat',
            name='img',
            field=models.ImageField(height_field='p_height', upload_to='images/cat/'),
        ),
        migrations.AlterField(
            model_name='pics',
            name='img',
            field=models.ImageField(blank=True, height_field='p_height', upload_to='images/pics/'),
        ),
    ]
